'''
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
Example 3:

Input: s = "a", t = "aa"
Output: "a"
Example 4:

Input: s = "ae", t = "aea"
Output: "a"
'''

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        alpha_1 = [0] * 26
        alpha_2 = [0] * 26
        
        for i in s:
            idx = ord(i) - 97
            alpha_1[idx] += 1
        
        for i in t:
            idx = ord(i) - 97
            alpha_2[idx] += 1
        
        
        for i in range(26):
            if alpha_1[i] != alpha_2[i]:
                return chr(i + 97)